services:
  crautos:
    build: ./CRAUTOS
    env_file:
      - .env
    ports:
      - "4321:4321"
    depends_on:
      - crautos-backend
    restart: always
    develop:
      watch:
        - action: sync+restart
          path: ./CRAUTOS
          target: /home/app
  crautos-backend:
    build: ./CRAUTOS-BACKEND
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: always
    develop:
      watch:
        - action: sync+restart
          path: ./CRAUTOS-BACKEND
          target: /home/app
  postgrest:
    image: postgrest/postgrest:latest
    ports:
      - "3001:3000"
    env_file:
      - .env
    restart: always
    depends_on:
      - postgres
  postgres:
    image: postgres:17
    volumes:
      - db_storage:/var/lib/postgresql
    restart: always
    env_file:
      - .env
    expose:
      - 5432
  pgadmin:
    image: dpage/pgadmin4:latest
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always
  swagger:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "8081:8080"
    env_file:
      - .env
    depends_on:
      - postgrest
    restart: always
volumes:
  db_storage:
  pgadmin_data:
